using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Da침oPlayer : MonoBehaviour
{
    private void OnCollisionEnter2D(Collision2D collision)
    {
        string tag = collision.gameObject.tag;

        if (tag == "Player")
        {
            collision.gameObject.SendMessage("ApplyDamage", 20, SendMessageOptions.RequireReceiver);
        }
        else if (tag == "Enemy")
        {
            // Aplicar da침o a los enemigos
            collision.gameObject.SendMessage("ApplyDamage", 10, SendMessageOptions.RequireReceiver);
        }
        else
        {
            // Aplicar da침o a otros objetos
            Debug.Log("Colisi칩n con: " + tag);
            collision.gameObject.SendMessage("ApplyDamage", 4, SendMessageOptions.DontRequireReceiver);
        }
    }
}

